name: release

on:
  push:
    branches:
      - "main"

jobs:
  release:
    name: Conditionally Release
    runs-on: ubuntu-latest

    permissions:
      contents: write
      packages: write
      attestations: write
      id-token: write

    steps:
      - uses: actions/checkout@v3
        with:
          token: ${{ secrets.GH_PAT }}
          clean: true
          fetch-depth: 0

      - name: build and test
        run: |
          make test
          go build

      - name: Attempt Release
        id: release
        run: |
          version=$(./release)
          echo "version=$version" >> $GITHUB_OUTPUT
        continue-on-error: true

      - name: Push Release Commit
        if: ${{ steps.release_check.outcome == 'success' }}
        run: |
          git push --tags
