name: release

on:
  push:
    branches:
      - "main"

jobs:
  release:
    name: Conditionally Release
    runs-on: ubuntu-latest

    permissions:
      contents: write
      packages: write
      attestations: write
      id-token: write

    steps:
      - uses: actions/checkout@v3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          clean: true

      - name: build and test
        run: |
          go test ./...
          go build

      - name: Attempt Release
        id: release
        run: |
          version=$(./release)
          echo "version=$version" >> $GITHUB_OUTPUT

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

        # check if theres an action for this
      - name: Log in to registry
        run: echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin

      - name: Build images
        env:
          GH_PAT: ${{ secrets.GH_PAT }}
        run: |
          docker buildx bake all

      - name: Push Release Commit
        if: steps.release.outcome == 'success'
        run: |
          git push
          git push --tags

      - name: Create GitHub Release
        if: steps.release.outcome == 'success'
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          gh release create ${{ steps.release.outputs.version }}

      - name: Upload Release Assets
        run: |
          gh release upload ${{ steps.release.outputs.version }} dist/*
