name: release

on:
  push:
    branches:
      - "main"

jobs:
  release:
    name: Conditionally Release
    runs-on: ubuntu-latest

    permissions:
      contents: write
      packages: write
      attestations: write
      id-token: write

    steps:
      - uses: actions/checkout@v3
        with:
          token: ${{ secrets.GH_PAT }}
          clean: true
          fetch-depth: 0

      - name: build and test
        run: |
          make test
          go build

      - name: Attempt Release
        id: release
        run: |
          version=$(./release)
          echo "version=$version" >> $GITHUB_OUTPUT

      - name: Push Release Commit
        run: |
          git push
          git push --tags
